# Data Analysis

## Notebook intro

In [1]:
1 + 1

2

In [2]:
my_string = "Chris' string"

In [5]:
print(my_string)
1+1

Chris' string


2

Now I no longer need quotes

It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)

## Numpy

In [6]:
import numpy as np # Canonical import

In [7]:
l = [[1,2,3], [4,5,6]]
print(type(l))
l # list of list

<class 'list'>


[[1, 2, 3], [4, 5, 6]]

In [14]:
A = np.array([[1,2,3.0], [4,5,6]]) 
print(type(A))
A # ndarray

<class 'numpy.ndarray'>


array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
# key Attributes of ndarrays
print('A.ndim: ', A.ndim)
print('A.shape:', A.shape)
print('A.size: ', A.size)
print('A.dtype:', A.dtype)

A.ndim:  2
A.shape: (2, 3)
A.size:  6
A.dtype: float64


### Data selection

In [16]:
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]
data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [18]:
data_list[2][1:4]

[21, 22, 23]

In [19]:
data_np[2, 1:4]

array([21, 22, 23])

In [24]:
# NumPy
data_np[1:, 4] # `1:` means from line 1 until the end.

array([14, 24, 34, 44])

In [25]:
A = np.arange(0, 10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
A[1:7:2]

array([1, 3, 5])

In [27]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Operations

In [28]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

In [29]:
# Python way
sums = []
for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator
sums

[11, 4, 11, 5, 10, 13, 8, 12]

In [30]:
A = np.array(my_list)
my_sum = A[:,0] + A[:,1] # Vectorial "+" operator
my_sum


array([11,  4, 11,  5, 10, 13,  8, 12])

In [33]:
# np.sum(A, axis=0)  # eq. to A[0,:] + A[1,:] + A[2,:] + ...
np.sum(A, axis=1)

array([11,  4, 11,  5, 10, 13,  8, 12])

In [34]:
np.sum(A)

74

### Boolean Indexing

In [36]:
A

array([[6, 5],
       [1, 3],
       [5, 6],
       [1, 4],
       [3, 7],
       [5, 8],
       [3, 5],
       [8, 4]])

In [39]:
A[A<=3] = 99

In [40]:
A

array([[ 6,  5],
       [99, 99],
       [ 5,  6],
       [99,  4],
       [99,  7],
       [ 5,  8],
       [99,  5],
       [ 8,  4]])

## Pandas

In [41]:
import pandas as pd


In [43]:
# s = pd.Series(data=[1,2,'three'], index=['id1', 'id2', 'id3'])
s = pd.Series({'id1': 1, 'id2': 2, 'id3': 'three'})
s

id1        1
id2        2
id3    three
dtype: object

In [45]:
s[1]

2

In [46]:
df = pd.DataFrame(
    [[4, 7, 10],
     [5, 8, 11],
     [6, 9, 12]],
    index=['row_1', 'row_2', 'row_3'],
    columns=["col_a", "col_b", "col_c"]
)
df

col_a  col_b  col_c
row_1      4      7     10
row_2      5      8     11
row_3      6      9     12

In [48]:
apples  = [1, 2, 3]
oranges = [4, 5, 6]
d = {
    "apples": apples,
    "oranges": oranges,
}
d
# pd.DataFrame(d)

{'apples': [1, 2, 3], 'oranges': [4, 5, 6]}