# NumPy

In [1]:
import numpy as np # Canonical import

## Types

In [2]:
# 1 type per array
I = np.array([[1,2,3], [4,5,6]])
display(I)
display(type(I[0,0]))

F = np.array([[1,2,3.0], [4,5,6]]) 
display(F)
display(type(F[0,0]))

S = np.array([[1,2,'3'], [4,5,6]]) 
display(S)
display(type(S[0,0]))

array([[1, 2, 3],
       [4, 5, 6]])

numpy.int64

array([[1., 2., 3.],
       [4., 5., 6.]])

numpy.float64

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

numpy.str_

In [3]:
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]
data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

## Slicing and Operations

In [4]:
# Rows - 1 and 2, all columns
display(data_np[1:3,:])

# Columns - 2, all rows
data_np[:,2]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

array([ 2, 12, 22, 32, 42])

In [38]:
# sum for each column
display(data_np.sum(axis=0))

# sum for each row
display(data_np.sum(axis=1))

# sum for our whole array
data_np.sum()

array([100, 105, 110, 115, 120])

array([ 10,  60, 110, 160, 210])

550

## Indexing

In [39]:
# Can check for an individual value by calling it on the whole array
data_np == 0

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [40]:
# Or something more complex like Odd vs even
data_np % 2 == 0

array([[ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True, False,  True]])

In [41]:
# We can assign the comparison to a variable and use that to index
even_mask = data_np % 2 == 0
data_np[even_mask]

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44])

In [42]:
# or wrap the comparison directly in [] to apply on the array
data_np[data_np % 2 == 0]

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44])

# Pandas

In [5]:
import pandas as pd

## Series

In [6]:
# A series is just a 1 dimensional - if you use a dictionary keys will become indexs
s = pd.Series({'id1': 1, 'id2': 2, 'id3': 'three'})
s

id1        1
id2        2
id3    three
dtype: object

In [45]:
# Indexes are not a column - this series has 3 rows and 0 columns
s.shape

(3,)

In [9]:
# They just take the place of the purely numerical index we are used to
type(s['id1'])

int

In [10]:
# If you pass a single list, numerical indexs will be assigned
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

## Dataframes

In [48]:
# We can make dataframes from a dictionary whose values are identical size lists:
d = {
    "apples": [1, 2, 3],
    "oranges": [4, 5, 6],
}
display(d)
pd.DataFrame(d)

{'apples': [1, 2, 3], 'oranges': [4, 5, 6]}

apples  oranges
0       1        4
1       2        5
2       3        6

In [49]:
# or a list full of dictionaries with identical keys
l = [{'apples': i, 'oranges':i+3} for i in range(1,4)]
display(l)
pd.DataFrame(l)

[{'apples': 1, 'oranges': 4},
 {'apples': 2, 'oranges': 5},
 {'apples': 3, 'oranges': 6}]

apples  oranges
0       1        4
1       2        5
2       3        6

## DF Manipulation

In [45]:
file = "countries.csv" # Path relative to your notebook
countries_df = pd.read_csv(file, decimal=',')

In [12]:
countries_df.head()

Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1         Albania   EASTERN EUROPE                          3581655   
2         Algeria   NORTHERN AFRICA                        32930091   
3  American Samoa   OCEANIA                                   57794   
4         Andorra   WESTERN EUROPE                            71201   

   Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
0          647500                        48.0                          0.00   
1           28748                       124.6                          1.26   
2         2381740                        13.8                          0.04   
3             199                       290.4                         58.29   
4             468                       152.1                          0.00   

   Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
0          23.06                              163.07               700.0   
1          -4.93                               21.52              4500.0   
2          -0.39                               31.00              6000.0   
3         -20.71                                9.27              8000.0   
4           6.60                                4.05             19000.0   

   Literacy (%)  Phones (per 1000)  Arable (%)  Crops (%)  Other (%)  Climate  \
0          36.0                3.2       12.13       0.22      87.65      1.0   
1          86.5               71.2       21.09       4.42      74.49      3.0   
2          70.0               78.1        3.22       0.25      96.53      1.0   
3          97.0              259.5       10.00      15.00      75.00      2.0   
4         100.0              497.2        2.22       0.00      97.78      3.0   

   Birthrate  Deathrate  Agriculture  Industry  Service  
0      46.60      20.34        0.380     0.240    0.380  
1      15.11       5.22        0.232     0.188    0.579  
2      17.14       4.61        0.101     0.600    0.298  
3      22.46       3.27          NaN       NaN      NaN  
4       8.71       6.25          NaN       NaN      NaN

### Selecting columns

In [13]:
# Using just one square bracket returns a SERIES
s = countries_df['Country']

display(type(s))
display(s.shape)
s.head()

pandas.core.series.Series

(227,)

0       Afghanistan 
1           Albania 
2           Algeria 
3    American Samoa 
4           Andorra 
Name: Country, dtype: object

In [14]:
# Using two square brackets keeps it as a 2D dataframe
d = countries_df[['Country']]

display(type(d))
display(d.shape)
d.head()

pandas.core.frame.DataFrame

(227, 1)

Country
0     Afghanistan 
1         Albania 
2         Algeria 
3  American Samoa 
4         Andorra

In [15]:
# Methods / attributes will be different based on what type of object you return
print('# of series options: ', len(dir(s)))
print('# of dataframe options: ', len(dir(d)))

# of series options:  433
# of dataframe options:  442


In [17]:
# BONUS - single "." notation for quickly returning series from column
countries_df.Country

0         Afghanistan 
1             Albania 
2             Algeria 
3      American Samoa 
4             Andorra 
            ...       
222         West Bank 
223    Western Sahara 
224             Yemen 
225            Zambia 
226          Zimbabwe 
Name: Country, Length: 227, dtype: object

### loc vs iloc

Now that we are no longer in standard python lists or numpy arrays we can be very specific with naming our row and column indexes

In [97]:
countries_df.head(2)

Country                               Region  Population  \
0  Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1      Albania   EASTERN EUROPE                          3581655   

   Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
0          647500                        48.0                          0.00   
1           28748                       124.6                          1.26   

   Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
0          23.06                              163.07               700.0   
1          -4.93                               21.52              4500.0   

   Literacy (%)  Phones (per 1000)  Arable (%)  Crops (%)  Other (%)  Climate  \
0          36.0                3.2       12.13       0.22      87.65      1.0   
1          86.5               71.2       21.09       4.42      74.49      3.0   

   Birthrate  Deathrate  Agriculture  Industry  Service  
0      46.60      20.34        0.380     0.240    0.380  
1      15.11       5.22        0.232     0.188    0.579

Right now our dataframe is using numerical indexes for rows (0,1 above) and string indexes for the columns ("Country", "Region", "Population").

In [18]:
# Indexing specific rows / columns with loc LOCATION, stop is included
# row indexs are still numerics at this point
countries_df.loc[0:1, 'Country':'Population']

Country                               Region  Population
0  Afghanistan         ASIA (EX. NEAR EAST)             31056997
1      Albania   EASTERN EUROPE                          3581655

In [19]:
# Indexing with iloc INDEX LOCATION is exclusive of the stop
# returns first row and first 2 columns
countries_df.iloc[0:2, 0:3]

Country                               Region  Population
0  Afghanistan         ASIA (EX. NEAR EAST)             31056997
1      Albania   EASTERN EUROPE                          3581655

So what's really happening?  First let's update the df with row indexes which aren't numerical

In [20]:
# Notice the column name dropped and the values are bold, these are now the indexes for our row
indexed_countries = countries_df.set_index('Country')
indexed_countries.head(3)

Region  Population  Area (sq. mi.)  \
Country                                                                         
Afghanistan         ASIA (EX. NEAR EAST)             31056997          647500   
Albania       EASTERN EUROPE                          3581655           28748   
Algeria       NORTHERN AFRICA                        32930091         2381740   

              Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
Country                                                                  
Afghanistan                         48.0                          0.00   
Albania                            124.6                          1.26   
Algeria                             13.8                          0.04   

              Net migration  Infant mortality (per 1000 births)  \
Country                                                           
Afghanistan           23.06                              163.07   
Albania               -4.93                               21.52   
Algeria               -0.39                               31.00   

              GDP ($ per capita)  Literacy (%)  Phones (per 1000)  Arable (%)  \
Country                                                                         
Afghanistan                700.0          36.0                3.2       12.13   
Albania                   4500.0          86.5               71.2       21.09   
Algeria                   6000.0          70.0               78.1        3.22   

              Crops (%)  Other (%)  Climate  Birthrate  Deathrate  \
Country                                                             
Afghanistan        0.22      87.65      1.0      46.60      20.34   
Albania            4.42      74.49      3.0      15.11       5.22   
Algeria            0.25      96.53      1.0      17.14       4.61   

              Agriculture  Industry  Service  
Country                                       
Afghanistan         0.380     0.240    0.380  
Albania             0.232     0.188    0.579  
Algeria             0.101     0.600    0.298

In [21]:
# Notice our .loc will no longer work if we pass an integer for the row - our new indexs are the country names
try:
    display(indexed_countries.loc[0:1, 'Country':'Population'])
except:
    print('Key Error')

Key Error


In [24]:
# We need to pass the string index for our row and remove country from our column selection
try:
    display(indexed_countries.loc['Afghanistan ': 'Albania ', 'Region':'Population'])
except:
    print('Key Error')

Region  Population
Country                                                      
Afghanistan         ASIA (EX. NEAR EAST)             31056997
Albania       EASTERN EUROPE                          3581655

In [25]:
# If we still want to use a numeric location we switch over to iloc and stop becomes exclusive
display(indexed_countries.iloc[0:2, 0:2])

Region  Population
Country                                                      
Afghanistan         ASIA (EX. NEAR EAST)             31056997
Albania       EASTERN EUROPE                          3581655

### Map function vs. calling function

In [26]:
# We can call methods () directly on a series
countries_df['Country'].str.upper()

0         AFGHANISTAN 
1             ALBANIA 
2             ALGERIA 
3      AMERICAN SAMOA 
4             ANDORRA 
            ...       
222         WEST BANK 
223    WESTERN SAHARA 
224             YEMEN 
225            ZAMBIA 
226          ZIMBABWE 
Name: Country, Length: 227, dtype: object

In [27]:
# Or map an uncalled function **notice - no ()** to the series
countries_df['Country'].map(str.upper)

0         AFGHANISTAN 
1             ALBANIA 
2             ALGERIA 
3      AMERICAN SAMOA 
4             ANDORRA 
            ...       
222         WEST BANK 
223    WESTERN SAHARA 
224             YEMEN 
225            ZAMBIA 
226          ZIMBABWE 
Name: Country, Length: 227, dtype: object

In [76]:
import math
countries_df['Population'].map(math.sqrt)

0      5572.880494
1      1892.526090
2      5738.474623
3       240.403827
4       266.835155
          ...     
222    1568.595550
223     522.501675
224    4632.082469
225    3391.461337
226    3498.114492
Name: Population, Length: 227, dtype: float64

### Group By

In [28]:
# Just using groupby returns an object
grouped_object = countries_df.groupby(by='Region')
grouped_object

In [175]:
print('Things to do with a dataframe: ',len(dir(countries_df)))
print('Things to do with grouped object: ',len(dir(grouped_object)))

Things to do with a dataframe:  450
Things to do with grouped object:  173


In [182]:
# We need to use an aggregation method to create a final df
print(type(grouped_object.sum()))
grouped_object.sum()

<class 'pandas.core.frame.DataFrame'>


Population  Area (sq. mi.)  \
Region                                                            
ASIA (EX. NEAR EAST)                 3687982236        23096712   
BALTICS                                 7184974          175015   
C.W. OF IND. STATES                   280081548        22100843   
EASTERN EUROPE                        119914717         1152222   
LATIN AMER. & CARIB                   561824599        20544084   
NEAR EAST                             195068377         4355586   
NORTHERN AFRICA                       161407133         6018890   
NORTHERN AMERICA                      331672307        21782471   
OCEANIA                                33131662         8519812   
SUB-SAHARAN AFRICA                    749437000        24341406   
WESTERN EUROPE                        396339998         3710478   

                                     Pop. Density (per sq. mi.)  \
Region                                                            
ASIA (EX. NEAR EAST)                                    35415.1   
BALTICS                                                   119.5   
C.W. OF IND. STATES                                       680.5   
EASTERN EUROPE                                           1210.8   
LATIN AMER. & CARIB                                      6129.1   
NEAR EAST                                                6833.3   
NORTHERN AFRICA                                           233.6   
NORTHERN AMERICA                                         1304.3   
OCEANIA                                                  2754.8   
SUB-SAHARAN AFRICA                                       4705.5   
WESTERN EUROPE                                          26657.2   

                                     Coastline (coast/area ratio)  \
Region                                                              
ASIA (EX. NEAR EAST)                                       501.95   
BALTICS                                                      9.35   
C.W. OF IND. STATES                                          1.12   
EASTERN EUROPE                                              12.42   
LATIN AMER. & CARIB                                        718.75   
NEAR EAST                                                   57.64   
NORTHERN AFRICA                                              1.91   
NORTHERN AMERICA                                           248.20   
OCEANIA                                                   2265.60   
SUB-SAHARAN AFRICA                                         260.41   
WESTERN EUROPE                                             727.18   

                                     Net migration  \
Region                                               
ASIA (EX. NEAR EAST)                         38.43   
BALTICS                                      -6.10   
C.W. OF IND. STATES                         -24.40   
EASTERN EUROPE                               -7.77   
LATIN AMER. & CARIB                         -67.25   
NEAR EAST                                    42.40   
NORTHERN AFRICA                              -2.16   
NORTHERN AMERICA                             -1.37   
OCEANIA                                     -39.15   
SUB-SAHARAN AFRICA                          -17.09   
WESTERN EUROPE                               93.00   

                                     Infant mortality (per 1000 births)  \
Region                                                                    
ASIA (EX. NEAR EAST)                                            1169.84   
BALTICS                                                           24.31   
C.W. OF IND. STATES                                              532.92   
EASTERN EUROPE                                                   152.24   
LATIN AMER. & CARIB                                              904.17   
NEAR EAST                                                        374.04   
NORTHERN AFRICA                                                  154.58   
NORTHERN AMERICA 

In [30]:
# If you know exactly which columns you want, its quicker to select them (by indexing) before aggregating 
grouped_object[['Population']].sum()

Population
Region                                         
ASIA (EX. NEAR EAST)                 3687982236
BALTICS                                 7184974
C.W. OF IND. STATES                   280081548
EASTERN EUROPE                        119914717
LATIN AMER. & CARIB                   561824599
NEAR EAST                             195068377
NORTHERN AFRICA                       161407133
NORTHERN AMERICA                      331672307
OCEANIA                                33131662
SUB-SAHARAN AFRICA                    749437000
WESTERN EUROPE                        396339998

In [54]:
# Using the agg funciton we can pass a dictionary with the different methods we want to use on different columns
display(countries_df.groupby(by='Region').agg({'Population':'sum', 'Birthrate':'mean'}))


# The long approach would be to run group by and aggs seperately and join them back together
s = countries_df.groupby(by='Region')[['Population']].sum()
m = countries_df.groupby(by='Region')[['Birthrate']].mean()
display(s.join(m))


Population  Birthrate
Region                                                    
ASIA (EX. NEAR EAST)                 3687982236  21.157857
BALTICS                                 7184974   9.343333
C.W. OF IND. STATES                   280081548  17.855833
EASTERN EUROPE                        119914717  10.370909
LATIN AMER. & CARIB                   561824599  19.081111
NEAR EAST                             195068377  25.031875
NORTHERN AFRICA                       161407133  20.814000
NORTHERN AMERICA                      331672307  13.154000
OCEANIA                                33131662  22.108000
SUB-SAHARAN AFRICA                    749437000  36.043922
WESTERN EUROPE                        396339998  10.553571

Population  Birthrate
Region                                                    
ASIA (EX. NEAR EAST)                 3687982236  21.157857
BALTICS                                 7184974   9.343333
C.W. OF IND. STATES                   280081548  17.855833
EASTERN EUROPE                        119914717  10.370909
LATIN AMER. & CARIB                   561824599  19.081111
NEAR EAST                             195068377  25.031875
NORTHERN AFRICA                       161407133  20.814000
NORTHERN AMERICA                      331672307  13.154000
OCEANIA                                33131662  22.108000
SUB-SAHARAN AFRICA                    749437000  36.043922
WESTERN EUROPE                        396339998  10.553571

In [36]:
countries_df.head()

Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1         Albania   EASTERN EUROPE                          3581655   
2         Algeria   NORTHERN AFRICA                        32930091   
3  American Samoa   OCEANIA                                   57794   
4         Andorra   WESTERN EUROPE                            71201   

   Area (sq. mi.)  Pop. Density (per sq. mi.)  Coastline (coast/area ratio)  \
0          647500                        48.0                          0.00   
1           28748                       124.6                          1.26   
2         2381740                        13.8                          0.04   
3             199                       290.4                         58.29   
4             468                       152.1                          0.00   

   Net migration  Infant mortality (per 1000 births)  GDP ($ per capita)  \
0          23.06                              163.07               700.0   
1          -4.93                               21.52              4500.0   
2          -0.39                               31.00              6000.0   
3         -20.71                                9.27              8000.0   
4           6.60                                4.05             19000.0   

   Literacy (%)  Phones (per 1000)  Arable (%)  Crops (%)  Other (%)  Climate  \
0          36.0                3.2       12.13       0.22      87.65      1.0   
1          86.5               71.2       21.09       4.42      74.49      3.0   
2          70.0               78.1        3.22       0.25      96.53      1.0   
3          97.0              259.5       10.00      15.00      75.00      2.0   
4         100.0              497.2        2.22       0.00      97.78      3.0   

   Birthrate  Deathrate  Agriculture  Industry  Service  
0      46.60      20.34        0.380     0.240    0.380  
1      15.11       5.22        0.232     0.188    0.579  
2      17.14       4.61        0.101     0.600    0.298  
3      22.46       3.27          NaN       NaN      NaN  
4       8.71       6.25          NaN       NaN      NaN

In [51]:
# This 
countries_df = countries_df.sort_values(by='Country', ascending=False)
# Does the same as this
countries_df.sort_values(by='Country', ascending=False, inplace=True)
# But never do this
# countries_df = countries_df.sort_values(by='Country', ascending=False, inplace=True)