# Numpy 101 

In [1]:
import numpy as np # Canonical import

## Creating and indexing

In [2]:
# Here a classic python list of list
l = [[1,2,3], [4,5,6]]
print(type(l))
l # list of list

<class 'list'>


[[1, 2, 3], [4, 5, 6]]

In [11]:
# we can create it instead as an ndarray
A = np.array([[1,2,3], [4,5,6]]) 
# or pass our list of list
# A = np.array(l) 

print(type(A))
A # ndarray

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# key Attributes of ndarrays
print('A.ndim: ', A.ndim)
print('A.shape:', A.shape)
print('A.size: ', A.size)
print('A.dtype:', A.dtype)

A.ndim:  2
A.shape: (2, 3)
A.size:  6
A.dtype: int64


In [13]:
# lets build a 2D array from a list of list
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]
data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### Indexing a row

In [14]:
# Pure python
data_list[2][1:4]

[21, 22, 23]

In [17]:
# NumPy
data_np[2, 1:4] # data_np[row(s), column(s)]

array([21, 22, 23])

### Indexing a column

In [18]:
# Pure python
selection = []
for index, row in enumerate(data_list):
    if index > 0:
        selection.append(row[4])
selection # We could also have used a list comprehension for less lines

[14, 24, 34, 44]

In [25]:
# NumPy
data_np[1:, 4] # `1:` means from line 1 until the end.

array([14, 24, 34, 44])

### Indexing with a step

In [26]:
A = np.arange(0, 10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
A[1:7:2]

array([1, 3, 5])

## Vectorized Operations

In [43]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

In [44]:
# Python way
sums = []
for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator
sums

[11, 4, 11, 5, 10, 13, 8, 12]

In [45]:
# Vectorized with slicing notation
A = np.array(my_list)
my_sum = A[:,0] + A[:,1] # Vectorial "+" operator
my_sum

array([11,  4, 11,  5, 10, 13,  8, 12])

In [46]:
A

array([[6, 5],
       [1, 3],
       [5, 6],
       [1, 4],
       [3, 7],
       [5, 8],
       [3, 5],
       [8, 4]])

In [47]:
# Vectorized with axis notation
# horizontal
np.sum(A, axis=1)  # eq. to A[:,0] + A[:,1] + A[:,2] + ...

array([11,  4, 11,  5, 10, 13,  8, 12])

In [48]:
# Vertical
np.sum(A, axis=0)  # eq. to A[:,0] + A[:,1] + A[:,2] + ...

array([32, 42])

## Boolean Indexing

In [34]:
A

array([[6, 5],
       [1, 3],
       [5, 6],
       [1, 4],
       [3, 7],
       [5, 8],
       [3, 5],
       [8, 4]])

In [37]:
# We can get our boolean mask with a comparison
A < 4

array([[False, False],
       [ True,  True],
       [False, False],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [False, False]])

In [49]:
# And index with that mask
A[A < 4]

array([1, 3, 1, 3, 3])

In [50]:
# Or reassign values with the mask
A[A < 4] = 99

In [51]:
A

array([[ 6,  5],
       [99, 99],
       [ 5,  6],
       [99,  4],
       [99,  7],
       [ 5,  8],
       [99,  5],
       [ 8,  4]])